"""Deterministic file enumeration — the [no model] front of the pipeline.

Walks a repo and filters out noise so the budget is spent on files worth
reading: vendored deps and build output (ignored dirs), boilerplate/config
(``__init__.py``, ``*.config.js``), and machine-generated code (DB migrations,
protobufs, codegen). It then applies a **per-directory cap** so no single folder
(a migrations dir, a generated-client dir) can monopolise the budget, and
exposes a `candidates` pool for the optional `select` stage to rank. Nothing
here calls a model: enumerating and bounding files is plain code.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from pathlib import Path

# Directories we never descend into. `migrations`/`alembic` hold auto-generated
# schema deltas — high count, near-zero architectural signal.
IGNORE_DIRS = {
    ".git", "node_modules", ".venv", "venv", "__pycache__", ".pytest_cache",
    ".ruff_cache", "dist", "build", "site", ".idea", ".vscode", ".mypy_cache",
    "vendor", "target", ".next", "coverage", "migrations", "alembic",
}

# Extensions we treat as analysable source. Anything else (images, binaries,
# lockfiles) is skipped — the LLM would learn nothing from them.
SOURCE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".go", ".rs", ".java", ".rb", ".php",
    ".c", ".h", ".cpp", ".hpp", ".cs", ".kt", ".swift", ".scala", ".sh",
    ".sql", ".vue", ".svelte",
}

# Exact filenames that are boilerplate or tooling config, never worth an LLM
# call: they carry little logic to map (empty package markers, thin shims, build
# and dependency scripts), so analysing them just burns tokens. Matched
# case-insensitively against the file name. Pattern-based configs (anything like
# `*.config.js` or `.eslintrc.*`) are caught by `_is_insignificant` instead, so
# we don't have to enumerate every tool here. Edit this to taste.
IGNORE_FILES = {
    "__init__.py",   # package marker — usually empty or pure re-exports
    "__main__.py",   # thin `python -m` shim
    "setup.py",      # packaging script, not product logic
    "conftest.py",   # pytest fixtures/config, not product logic
    "manage.py",     # Django CLI shim
    "gulpfile.js",
    "gruntfile.js",
    "env.py",        # environment/config loader, not product logic
    # Deployment / release / ops scripts — infrastructure, not app architecture.
    "docker-entrypoint.sh",
    "version.sh",
    "create_release.sh",
    "helper.sh",
    "vault_login_and_agent.sh",
}


def _is_insignificant(name: str) -> bool:
    """True for boilerplate/config files that aren't worth an LLM call."""
    low = name.lower()
    if low in IGNORE_FILES:
        return True
    # Tooling config written in a code language: vite/webpack/jest/babel/tailwind/
    # postcss/next/rollup/karma/... all match one of these shapes.
    if (".config." in low or ".conf." in low) and low.endswith((".js", ".ts", ".mjs", ".cjs")):
        return True
    if low.startswith((".eslintrc", ".prettierrc", ".babelrc", ".stylelintrc")):
        return True
    # Kubernetes tooling/config (kube_ps1.sh, kubeconfig, kubectl wrappers, …).
    if low.startswith("kube"):
        return True
    # Shell helper/ops scripts (azure_helper.sh, vault_helper.sh, …) — glue, not
    # application architecture.
    if low.endswith("_helper.sh"):
        return True
    return False


# Machine-generated files: high count, near-zero value to a human reader. We
# catch them two ways — a filename pattern (cheap) and a content sniff (robust),
# because a generated file isn't always in a tell-tale directory.
_GENERATED_NAME_RE = re.compile(
    r"^[0-9a-f]{8,}_"            # migration hash prefix: 23dc86b92f42_add_x.py
    r"|_pb2(_grpc)?\.py$"        # protobuf
    r"|\.generated\."            # *.generated.*
    r"|\.g\.dart$"               # dart codegen
    r"|\.min\.(js|css)$",        # minified bundles
    re.IGNORECASE,
)
# Markers generators conventionally stamp near the top of a file.
_GENERATED_MARKERS = (
    b"@generated", b"do not edit", b"code generated by", b"autogenerated",
    b"down_revision",            # alembic migration body
)
_GENERATED_SNIFF_BYTES = 1024


def _is_generated(path: Path) -> bool:
    """True for machine-generated files (migrations, protobufs, codegen)."""
    if _GENERATED_NAME_RE.search(path.name):
        return True
    try:
        with path.open("rb") as fh:
            head = fh.read(_GENERATED_SNIFF_BYTES).lower()
    except OSError:
        return False
    return any(marker in head for marker in _GENERATED_MARKERS)


# No single directory may consume more than this fraction of the file budget, so
# a big folder (migrations, generated clients, a flat test dir) can't crowd out
# the rest of the codebase. Backfilled only if slots remain after the capped pass.
_DIR_CAP_FRACTION = 0.34

# Upper bound on the candidate pool handed to the `select` stage — keeps that
# prompt cheap even on huge repos (paths only, but still).
SELECT_POOL_MAX = 200


def _apply_dir_cap(sorted_paths: list[Path], max_files: int) -> list[Path]:
    """Pick up to ``max_files`` paths, capping how many come from any one directory.

    Walks the importance-sorted list keeping at most ``ceil(max_files * fraction)``
    per directory; if budget remains after that pass (because some dirs hit the
    cap), backfills from the held-back files. Prevents a single folder from
    monopolising the budget without ever leaving slots unused.
    """
    if max_files <= 0:
        return []
    per_dir = max(1, math.ceil(max_files * _DIR_CAP_FRACTION))
    counts: dict[Path, int] = {}
    primary: list[Path] = []
    overflow: list[Path] = []
    for path in sorted_paths:
        directory = path.parent
        if counts.get(directory, 0) < per_dir:
            counts[directory] = counts.get(directory, 0) + 1
            primary.append(path)
        else:
            overflow.append(path)
    kept = primary[:max_files]
    if len(kept) < max_files:
        kept += overflow[: max_files - len(kept)]
    return kept


# Map extension -> language label for the project summary.
_LANG_BY_EXT = {
    ".py": "Python", ".js": "JavaScript", ".jsx": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".go": "Go", ".rs": "Rust", ".java": "Java", ".rb": "Ruby",
    ".php": "PHP", ".c": "C", ".h": "C", ".cpp": "C++", ".hpp": "C++", ".cs": "C#",
    ".kt": "Kotlin", ".swift": "Swift", ".scala": "Scala", ".sh": "Shell",
    ".sql": "SQL", ".vue": "Vue", ".svelte": "Svelte",
}

DEFAULT_MAX_FILES = 30
MAX_FILE_BYTES = 100_000  # skip files larger than ~100KB (generated/minified)

# Filenames treated as entry points — sorted first so truncation keeps them.
_ENTRYPOINTS = {"main.py", "app.py", "index.js", "index.ts", "cli.py"}


@dataclass
class ScanResult:
    root: Path
    files: list[str]          # deterministic pick (dir-capped), the fallback selection
    total_found: int          # how many matched before the cap
    truncated: bool           # True when total_found exceeded the cap
    languages: list[str]
    candidates: list[str] = field(default_factory=list)  # full filtered pool for `select`


def enumerate_source_files(root: str | Path, max_files: int = DEFAULT_MAX_FILES) -> ScanResult:
    """Return analysable source files under ``root`` (relative paths).

    Filters noise (ignored dirs, boilerplate/config, machine-generated files),
    sorts by a cheap importance heuristic (entry points first, then shallower
    paths), and produces TWO views: ``files`` is the deterministic pick with a
    per-directory cap applied (used directly when the `select` stage is skipped),
    and ``candidates`` is the fuller filtered pool the `select` stage ranks.
    Truncation is recorded on the result, never silent.
    """
    root = Path(root)
    found: list[Path] = []
    for path in root.rglob("*"):
        if path.is_dir():
            continue
        if any(part in IGNORE_DIRS for part in path.parts):
            continue
        if path.suffix.lower() not in SOURCE_EXTENSIONS:
            continue
        if _is_insignificant(path.name):
            continue
        try:
            if path.stat().st_size > MAX_FILE_BYTES:
                continue
        except OSError:
            continue
        if _is_generated(path):
            continue
        found.append(path)

    found.sort(key=lambda p: _importance_key(p, root))
    total = len(found)
    kept = _apply_dir_cap(found, max_files)

    rel = [str(p.relative_to(root)) for p in kept]
    candidates = [str(p.relative_to(root)) for p in found[:SELECT_POOL_MAX]]
    languages = sorted(
        {_LANG_BY_EXT[p.suffix.lower()] for p in found if p.suffix.lower() in _LANG_BY_EXT}
    )
    return ScanResult(
        root=root,
        files=rel,
        total_found=total,
        truncated=total > len(kept),
        languages=languages,
        candidates=candidates,
    )


def _importance_key(path: Path, root: Path) -> tuple:
    """Lower sorts first. Prefer entry points, then shallower paths, then name."""
    entrypoint = 0 if path.name.lower() in _ENTRYPOINTS else 1
    depth = len(path.relative_to(root).parts)
    return (entrypoint, depth, str(path).lower())


def read_text(root: str | Path, rel_path: str, max_bytes: int = MAX_FILE_BYTES) -> str:
    """Read a file's text, tolerant of encoding issues and truncated to ``max_bytes``."""
    full = Path(root) / rel_path
    data = full.read_bytes()[:max_bytes]
    return data.decode("utf-8", errors="replace")
