"""Enumeration must ignore noise, cap the count, and SURFACE truncation —
a silent cap would make a partial analysis look complete.
"""

from pipeline.files import enumerate_source_files, read_text


def _make_repo(root):
    (root / "main.py").write_text("print('hi')\n")
    (root / "util.py").write_text("x = 1\n")
    (root / "README.md").write_text("# docs\n")            # not source -> skipped
    (root / "node_modules").mkdir()
    (root / "node_modules" / "dep.js").write_text("//noise\n")  # ignored dir
    (root / "src").mkdir()
    (root / "src" / "app.py").write_text("y = 2\n")


def test_enumerate_filters_noise_and_detects_language(tmp_path):
    _make_repo(tmp_path)
    result = enumerate_source_files(tmp_path)
    assert "main.py" in result.files
    assert "README.md" not in result.files                 # non-source skipped
    assert all("node_modules" not in f for f in result.files)  # ignored dir
    assert result.languages == ["Python"]
    assert not result.truncated


def test_truncation_is_recorded_not_silent(tmp_path):
    for i in range(10):
        (tmp_path / f"f{i}.py").write_text("a = 1\n")
    result = enumerate_source_files(tmp_path, max_files=3)
    assert len(result.files) == 3
    assert result.truncated is True
    assert result.total_found == 10


def test_entrypoints_survive_truncation(tmp_path):
    # If we can only keep a few files, keep the entry point over a deep helper.
    (tmp_path / "main.py").write_text("a = 1\n")
    deep = tmp_path / "a" / "b" / "c"
    deep.mkdir(parents=True)
    (deep / "helper.py").write_text("a = 1\n")
    result = enumerate_source_files(tmp_path, max_files=1)
    assert result.files == ["main.py"]


def test_skips_boilerplate_and_config_files(tmp_path):
    # Real logic is kept; boilerplate/config that would just burn tokens is dropped.
    (tmp_path / "service.py").write_text("def work(): ...\n")   # kept
    (tmp_path / "__init__.py").write_text("from .service import work\n")
    (tmp_path / "setup.py").write_text("setup()\n")
    (tmp_path / "conftest.py").write_text("import pytest\n")
    (tmp_path / "vite.config.js").write_text("export default {}\n")
    (tmp_path / ".eslintrc.js").write_text("module.exports = {}\n")
    (tmp_path / "env.py").write_text("import os\n")
    (tmp_path / "docker-entrypoint.sh").write_text("#!/bin/sh\n")
    (tmp_path / "kube_ps1.sh").write_text("#!/bin/sh\n")        # kube* infra tooling
    (tmp_path / "azure_helper.sh").write_text("#!/bin/sh\n")    # *_helper.sh ops glue
    (tmp_path / "vault_helper.sh").write_text("#!/bin/sh\n")
    (tmp_path / "helper.sh").write_text("#!/bin/sh\n")
    (tmp_path / "vault_login_and_agent.sh").write_text("#!/bin/sh\n")
    result = enumerate_source_files(tmp_path)
    assert result.files == ["service.py"]
    assert result.total_found == 1            # skipped files don't inflate the count


def test_keeps_procedural_app_scripts_with_no_members(tmp_path):
    # 0 top-level functions/classes does NOT mean unnecessary — these are real
    # application scripts and must be analysed, unlike infra/config files.
    (tmp_path / "get_report.py").write_text("print('report')\n")
    (tmp_path / "inspect_alert.py").write_text("print('alert')\n")
    result = enumerate_source_files(tmp_path)
    assert set(result.files) == {"get_report.py", "inspect_alert.py"}


def test_init_py_is_not_a_kept_entrypoint(tmp_path):
    # __init__.py used to be prioritised as an entry point; it must now be skipped
    # entirely, so a real source file wins the single slot.
    (tmp_path / "__init__.py").write_text("x = 1\n")
    (tmp_path / "core.py").write_text("y = 2\n")
    result = enumerate_source_files(tmp_path, max_files=1)
    assert result.files == ["core.py"]


def test_skips_generated_and_migration_files(tmp_path):
    (tmp_path / "service.py").write_text("def work(): ...\n")           # kept
    (tmp_path / "23dc86b92f42_add_ou_columns.py").write_text(            # alembic hash name
        "down_revision = 'abc'\n"
    )
    (tmp_path / "orders_pb2.py").write_text("# protobuf\n")              # _pb2 name
    (tmp_path / "bundle.generated.js").write_text("export {}\n")         # *.generated.*
    (tmp_path / "schema_gen.py").write_text("# @generated by tool\nx=1\n")  # content sniff
    result = enumerate_source_files(tmp_path)
    assert result.files == ["service.py"]


def test_migrations_and_alembic_directories_are_ignored(tmp_path):
    (tmp_path / "app.py").write_text("a = 1\n")
    for d in ("migrations", "alembic"):
        sub = tmp_path / d / "versions"
        sub.mkdir(parents=True)
        (sub / "0001_change.py").write_text("a = 1\n")
    result = enumerate_source_files(tmp_path)
    assert result.files == ["app.py"]


def test_dir_cap_stops_one_directory_monopolising_the_budget(tmp_path):
    # 20 files in api/, 2 in core/, plus an entry point. Without a per-dir cap the
    # first 6 would be main.py + 5 api files — core/ starved. The cap must keep core.
    (tmp_path / "main.py").write_text("a = 1\n")
    api = tmp_path / "api"; api.mkdir()
    for i in range(20):
        (api / f"m{i:02d}.py").write_text("a = 1\n")
    core = tmp_path / "core"; core.mkdir()
    (core / "c0.py").write_text("a = 1\n")
    (core / "c1.py").write_text("a = 1\n")

    result = enumerate_source_files(tmp_path, max_files=6)
    assert len(result.files) == 6
    assert "main.py" in result.files
    assert "core/c0.py" in result.files and "core/c1.py" in result.files  # not starved
    assert sum(f.startswith("api/") for f in result.files) == 3           # capped at ~1/3
    assert result.total_found == 23                                        # full pool counted


def test_candidates_pool_holds_the_full_filtered_set(tmp_path):
    for i in range(5):
        (tmp_path / f"f{i}.py").write_text("a = 1\n")
    result = enumerate_source_files(tmp_path, max_files=2)
    assert len(result.files) == 2          # deterministic pick is capped
    assert len(result.candidates) == 5     # but the select pool sees everything


def test_read_text_tolerates_bad_encoding(tmp_path):
    (tmp_path / "weird.py").write_bytes(b"x = '\xff\xfe'\n")
    text = read_text(tmp_path, "weird.py")
    assert "x =" in text  # decoded with replacement, did not raise
